version: '3.8'
services:
  esdc_server_container:
    build:
      context: .
      dockerfile: Dockerfile
    image: esdc_server
    container_name: esdc_server_container
    ports:
      - 8082:8080
    volumes:
      - ./:/app
    networks:
      - esdc_server
    depends_on:
      - docker-mysql
    environment:
      SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/ffms_refactor?characterEncoding=UTF-8:
  docker-mysql:
    image: mysql:latest
    ports:
      - 3307:3306
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - esdc_server
    environment:
      MYSQL_DATABASE: ffms_refactor
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
volumes:
  mysql_data:
networks:
  esdc_server:
